// next.config.mjs (ESM)
// Redirects auto-generated from old WordPress sitemap → new Next.js routes.

import path from 'path';

/** @type {import('next').NextConfig} */
const nextConfig = {
  async redirects() {
    // inside redirects()
return [
  { source: '/par-mums/:path*', destination: '/par-mums', permanent: true },
  { source: '/plansetdatoru-remonts/:path*', destination: '/plansetdatoru-remonts', permanent: true },

  { source: '/samsung-galaxy-note-7-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-tab-s5e-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-tab-a10-1-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-xcover-4s-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-m40-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-m30-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-m20-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-m10-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a30s-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a20s-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a70-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a60-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a50-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a40-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a30-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a20-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a10-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a9-2018-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a7-2018-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a6-plus-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a6-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a8-star-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a8-plus-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a8-2018-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a7-2017-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a5-2017-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a3-2017-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a7-2016-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a5-2016-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-a3-2016-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },

  { source: '/samsung-galaxy-j8-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-j7-2017-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-j6-plus-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-j6-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-j5-2017-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-j4-plus-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-j4-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-j3-2017-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-j7-prime-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-j5-prime-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-j2-prime-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-j1-2016-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-j5-2016-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-j3-2016-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-j1-mini-prime-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-j1-nxt-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-j1-ace-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-j1-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },

  { source: '/samsung-galaxy-note-9-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-note-8-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-note-5-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-note-4-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-note-3-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },

  { source: '/samsung-galaxy-s10-5g-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s10-plus-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s10-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s10e-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s9-plus-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s9-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s8-plus-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s8-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s7-edge-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s7-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s6-edge-plus-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s6-edge-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s6-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s5-neo-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s5-mini-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s5-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s4-mini-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s4-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s3-neo-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s3-mini-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s3-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },

  { source: '/huawei-y5-2019-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p30-pro-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p30-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p30-lite-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p20-pro-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p20-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p20-lite-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p10-plus-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p10-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p10-lite-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p9-plus-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p9-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p9-lite-mini-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p9-lite-2017-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p9-lite-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p8-max-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p8-lite-2017-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p8-lite-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p8-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },

  { source: '/huawei-mate-20-pro-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-mate-20-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-mate-20-lite-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-mate-10-pro-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-mate-10-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-mate-10-lite-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-mate-9-pro-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-mate-9-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-mate-8-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-mate-s-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },

  { source: '/huawei-nova-5t-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-nova-4-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-nova-3i-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-nova-3-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-nova-2-plus-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-nova-2-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },

  { source: '/huawei-y9-2019-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-y9-prime-2019-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-y7-2019-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-y7-prime-2018-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-y6-prime-2018-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-y6-2018-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-y5-2018-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-y7-2018-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-y7-2017-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-y6-2017-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-y5-2017-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-y3-2017-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },

  { source: '/huawei-y6-ii-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-y5-ii-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-y3-ii-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-y6-pro-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-y6-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-y5-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-y3-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },

  { source: '/huawei-p-smart-2019-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p-smart-2018-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p-smart-plus-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },
  { source: '/huawei-p-smart-z-remonts/:path*', destination: '/telefonu-remonts/huawei', permanent: true },

  { source: '/oneplus-7-pro-remonts/:path*', destination: '/telefonu-remonts/oneplus', permanent: true },
  { source: '/oneplus-7-remonts/:path*', destination: '/telefonu-remonts/oneplus', permanent: true },
  { source: '/oneplus-6t-remonts/:path*', destination: '/telefonu-remonts/oneplus', permanent: true },
  { source: '/oneplus-6-remonts/:path*', destination: '/telefonu-remonts/oneplus', permanent: true },
  { source: '/oneplus-5t-remonts/:path*', destination: '/telefonu-remonts/oneplus', permanent: true },
  { source: '/oneplus-5-remonts/:path*', destination: '/telefonu-remonts/oneplus', permanent: true },
  { source: '/oneplus-3t-remonts/:path*', destination: '/telefonu-remonts/oneplus', permanent: true },
  { source: '/oneplus-3-remonts/:path*', destination: '/telefonu-remonts/oneplus', permanent: true },
  { source: '/oneplus-x-remonts/:path*', destination: '/telefonu-remonts/oneplus', permanent: true },
  { source: '/oneplus-2-remonts/:path*', destination: '/telefonu-remonts/oneplus', permanent: true },
  { source: '/oneplus-one-remonts/:path*', destination: '/telefonu-remonts/oneplus', permanent: true },

  { source: '/lenovo-k6-note-remonts/:path*', destination: '/telefonu-remonts/lenovo', permanent: true },
  { source: '/lenovo-k6-remonts/:path*', destination: '/telefonu-remonts/lenovo', permanent: true },
  { source: '/lenovo-vibe-shot-remonts/:path*', destination: '/telefonu-remonts/lenovo', permanent: true },
  { source: '/lenovo-vibe-s1-remonts/:path*', destination: '/telefonu-remonts/lenovo', permanent: true },
  { source: '/lenovo-vibe-p1m-remonts/:path*', destination: '/telefonu-remonts/lenovo', permanent: true },
  { source: '/lenovo-a6000-plus-remonts/:path*', destination: '/telefonu-remonts/lenovo', permanent: true },
  { source: '/lenovo-a6000-remonts/:path*', destination: '/telefonu-remonts/lenovo', permanent: true },
  { source: '/lenovo-a5000-remonts/:path*', destination: '/telefonu-remonts/lenovo', permanent: true },
  { source: '/lenovo-a319-remonts/:path*', destination: '/telefonu-remonts/lenovo', permanent: true },
  { source: '/lenovo-a316i-remonts/:path*', destination: '/telefonu-remonts/lenovo', permanent: true },
  { source: '/lenovo-a328-remonts/:path*', destination: '/telefonu-remonts/lenovo', permanent: true },

  { source: '/sony-xperia-xz3-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-xz2-premium-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-xz2-compact-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-xz2-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-xz1-compact-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-xz1-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-xz-premium-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-xz-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-x-compact-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-x-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-xa2-ultra-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-xa2-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-xa1-ultra-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-xa1-plus-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-xa1-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-xa-ultra-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-xa-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-m5-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-m4-aqua-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-z5-premium-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-z5-compact-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-z5-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-z3-plus-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-z3-compact-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-z3-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-z2-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-z1-compact-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-z1-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-z-ultra-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },
  { source: '/sony-xperia-z-remonts/:path*', destination: '/telefonu-remonts/sony', permanent: true },

  { source: '/iphone-xs-max-remonts/:path*', destination: '/iphone-remonts/iphone-xs-max', permanent: true },
  { source: '/iphone-xs-remonts/:path*', destination: '/iphone-remonts/iphone-xs', permanent: true },
  { source: '/iphone-xr-remonts/:path*', destination: '/iphone-remonts/iphone-xr', permanent: true },
  { source: '/iphone-x-remonts/:path*', destination: '/iphone-remonts/iphone-x', permanent: true },
  { source: '/iphone-8-plus-remonts/:path*', destination: '/iphone-remonts/iphone-8-plus', permanent: true },
  { source: '/iphone-8-remonts/:path*', destination: '/iphone-remonts/iphone-8', permanent: true },
  { source: '/iphone-7-plus-remonts/:path*', destination: '/iphone-remonts/iphone-7-plus', permanent: true },
  { source: '/iphone-7-remonts/:path*', destination: '/iphone-remonts/iphone-7', permanent: true },
  { source: '/iphone-6s-plus-remonts/:path*', destination: '/iphone-remonts/iphone-6s-plus', permanent: true },
  { source: '/iphone-6s-remonts/:path*', destination: '/iphone-remonts/iphone-6s', permanent: true },
  { source: '/iphone-6-plus-remonts/:path*', destination: '/iphone-remonts/iphone-6-plus', permanent: true },
  { source: '/iphone-6-remonts/:path*', destination: '/iphone-remonts/iphone-6', permanent: true },
  { source: '/iphone-se-2016-remonts/:path*', destination: '/iphone-remonts/iphone-se-2016', permanent: true },
  { source: '/iphone-5s-remonts/:path*', destination: '/iphone-remonts/iphone-5s', permanent: true },
  { source: '/iphone-5c-remonts/:path*', destination: '/iphone-remonts/iphone-5c', permanent: true },
  { source: '/iphone-5-remonts/:path*', destination: '/iphone-remonts/iphone-5', permanent: true },

  { source: '/apple-ipad-pro-remonts-12-9/:path*', destination: '/plansetdatoru-remonts/ipad', permanent: true },
  { source: '/apple-ipad-pro-2-remonts-12-9/:path*', destination: '/plansetdatoru-remonts/ipad', permanent: true },
  { source: '/apple-ipad-pro-2-remonts-10-5/:path*', destination: '/plansetdatoru-remonts/ipad', permanent: true },
  { source: '/apple-ipad-pro-3-remonts-12-9/:path*', destination: '/plansetdatoru-remonts/ipad', permanent: true },
  { source: '/apple-ipad-pro-4-remonts-11/:path*', destination: '/plansetdatoru-remonts/ipad', permanent: true },
  { source: '/apple-ipad-pro-3-remonts-11/:path*', destination: '/plansetdatoru-remonts/ipad', permanent: true },
  { source: '/apple-ipad-pro-4-remonts-12-9/:path*', destination: '/plansetdatoru-remonts/ipad', permanent: true },
  { source: '/apple-ipad-pro-5-remonts-12-9/:path*', destination: '/plansetdatoru-remonts/ipad', permanent: true },
  { source: '/apple-ipad-pro-5-remonts-11/:path*', destination: '/plansetdatoru-remonts/ipad', permanent: true },
  { source: '/apple-ipad-pro-remonts-9-7/:path*', destination: '/plansetdatoru-remonts/ipad', permanent: true },
  { source: '/apple-ipad-air-2-remonts-2/:path*', destination: '/plansetdatoru-remonts/ipad', permanent: true },

  { source: '/macbook-remonts/:path*', destination: '/datoru-remonts/apple', permanent: true },
  { source: '/macbook-pro-remonts/:path*', destination: '/datoru-remonts/apple', permanent: true },
  { source: '/macbook-air-remonts/:path*', destination: '/datoru-remonts/apple', permanent: true },

  { source: '/samsung-galaxy-a30-remonts-3/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s20-fe-remonts-2/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s10e-remonts-3/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-s23-fe-remonts-copy/:path*', destination: '/telefonu-remonts/samsung', permanent: true },
  { source: '/samsung-galaxy-note-10-remonts-3/:path*', destination: '/telefonu-remonts/samsung', permanent: true },

  // ADD these after your existing redirects
{ source: '/paldies/:path*', destination: '/pieraksties', permanent: true },
{ source: '/products/:path*', destination: '/', permanent: true },
{ source: '/nosutit-telefonu/:path*', destination: '/kontakti', permanent: true },

// MacBook model pages → MacBook hub
{ source: '/macbook-air-remonts-a1466/:path*', destination: '/datoru-remonts/macbook', permanent: true },
{ source: '/macbook-air-remonts-a1932/:path*', destination: '/datoru-remonts/macbook', permanent: true },
{ source: '/macbook-air-remonts-a2179/:path*', destination: '/datoru-remonts/macbook', permanent: true },
{ source: '/macbook-air-remonts-a2337/:path*', destination: '/datoru-remonts/macbook', permanent: true },
{ source: '/macbook-pro-remonts-a1502/:path*', destination: '/datoru-remonts/macbook', permanent: true },
{ source: '/macbook-pro-remonts-a1707/:path*', destination: '/datoru-remonts/macbook', permanent: true },
{ source: '/macbook-pro-remonts-a1708/:path*', destination: '/datoru-remonts/macbook', permanent: true },
{ source: '/macbook-pro-remonts-a1989/:path*', destination: '/datoru-remonts/macbook', permanent: true },
{ source: '/macbook-pro-remonts-a2141/:path*', destination: '/datoru-remonts/macbook', permanent: true },
{ source: '/macbook-pro-remonts-a2159/:path*', destination: '/datoru-remonts/macbook', permanent: true },
{ source: '/macbook-pro-remonts-a2251/:path*', destination: '/datoru-remonts/macbook', permanent: true },
{ source: '/macbook-pro-remonts-a2289/:path*', destination: '/datoru-remonts/macbook', permanent: true },
{ source: '/macbook-pro-remonts-a2338/:path*', destination: '/datoru-remonts/macbook', permanent: true },
{ source: '/macbook-pro-remonts-a2442/:path*', destination: '/datoru-remonts/macbook', permanent: true },
{ source: '/macbook-pro-remonts-a2485/:path*', destination: '/datoru-remonts/macbook', permanent: true },
{ source: '/macbook-retina-remonts-a1534/:path*', destination: '/datoru-remonts/macbook', permanent: true },
{ source: '/macbook-pro-remonts-a1706/:path*', destination: '/datoru-remonts/macbook', permanent: true },

// Old iPad models & hubs
{ source: '/ipad-remonts/:path*', destination: '/plansetdatoru-remonts/ipad', permanent: true },

{ source: '/apple-ipad-air-5-remonts/:path*', destination: '/plansetdatoru-remonts/ipad/air-10-5-3rd-gen-2019', permanent: true },
{ source: '/apple-ipad-mini-2-remonts/:path*', destination: '/plansetdatoru-remonts/ipad/mini-4th-gen-2015', permanent: true },
{ source: '/apple-ipad-mini-3-remonts/:path*', destination: '/plansetdatoru-remonts/ipad/pro-13-m4-2024', permanent: true },
{ source: '/apple-ipad-mini-1-remonts/:path*', destination: '/plansetdatoru-remonts/ipad/mini-4th-gen-2015', permanent: true },
{ source: '/apple-ipad-mini-6-remonts/:path*', destination: '/plansetdatoru-remonts/ipad/mini-6th-gen-2021', permanent: true },
{ source: '/apple-ipad-air-remonts/:path*', destination: '/plansetdatoru-remonts/ipad/air-1st-gen-2013', permanent: true },

{ source: '/apple-ipad-5-remonts/:path*', destination: '/plansetdatoru-remonts/ipad/pro-10-5-2017', permanent: true },
{ source: '/apple-ipad-6-remonts/:path*', destination: '/plansetdatoru-remonts/ipad/pro-9-7-2016', permanent: true },
{ source: '/apple-ipad-7-remonts/:path*', destination: '/plansetdatoru-remonts/ipad/pro-9-7-2016', permanent: true },
{ source: '/apple-ipad-8-remonts/:path*', destination: '/plansetdatoru-remonts/ipad/pro-11-2018', permanent: true },
{ source: '/apple-ipad-9-remonts/:path*', destination: '/plansetdatoru-remonts/ipad/pro-9-7-2016', permanent: true },

// You already have /apple-ipad-pro-*/ and /apple-ipad-air-2-remonts-2/
// but these two were missing:
{ source: '/apple-ipad-air-3-remonts/:path*', destination: '/plansetdatoru-remonts/ipad/air-1st-gen-2013', permanent: true },
{ source: '/apple-ipad-air-4-remonts/:path*', destination: '/plansetdatoru-remonts/ipad/air-2nd-gen-2014', permanent: true },

{ source: '/apple-ipad-mini-5-remonts/:path*', destination: '/plansetdatoru-remonts/ipad/mini-4th-gen-2015', permanent: true },
{ source: '/apple-ipad-mini-4-remonts/:path*', destination: '/plansetdatoru-remonts/ipad/mini-4th-gen-2015', permanent: true },

// Laptop brand hubs (very important)
{ source: '/acer-datoru-remonts/:path*', destination: '/datoru-remonts/acer', permanent: true },
{ source: '/asus-datoru-remonts/:path*', destination: '/datoru-remonts/asus', permanent: true },
{ source: '/dell-datoru-remonts/:path*', destination: '/datoru-remonts/dell', permanent: true },
{ source: '/hp-datoru-remonts/:path*', destination: '/datoru-remonts/hp', permanent: true },
{ source: '/lenovo-datoru-remonts/:path*', destination: '/datoru-remonts/lenovo', permanent: true },
{ source: '/samsung-datoru-remonts/:path*', destination: '/datoru-remonts/samsung', permanent: true },

// Phone brand hubs (some you already have; these two were missing)
{ source: '/xiaomi-telefonu-remonts/:path*', destination: '/telefonu-remonts/xiaomi', permanent: true },
{ source: '/samsung-telefonu-remonts/:path*', destination: '/telefonu-remonts/samsung', permanent: true },



];

  },

  webpack: (config) => {
    config.resolve.alias = {
      ...config.resolve.alias,
      '@': path.resolve(process.cwd()),           // root alias
      '@lib': path.resolve(process.cwd(), 'lib'),
      '@data': path.resolve(process.cwd(), 'app/data'),
      '@sections': path.resolve(process.cwd(), 'app/(site)/sections'),
      '@screens': path.resolve(process.cwd(), 'app/(site)/screens'),
      '@ui': path.resolve(process.cwd(), 'app/(site)/ui'),
      '@styles': path.resolve(process.cwd(), 'app/styles'),
      '@components': path.resolve(process.cwd(), 'app/(site)/components'),
    };
    return config;
  },
};

export default nextConfig;
