// next.config.mjs (ESM)
// Redirects auto-generated from old WordPress sitemap → new Next.js routes.

import path from 'path';

/** @type {import('next').NextConfig} */
const nextConfig = {
  async redirects() {
    return [
      { source: '/par-mums/', destination: '/par-mums', permanent: true },
      { source: '/plansetdatoru-remonts/', destination: '/plansetdatoru-remonts', permanent: true },
      { source: '/samsung-galaxy-note-7-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-tab-s5e-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-tab-a10-1-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-xcover-4s-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-m40-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-m30-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-m20-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-m10-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a30s-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a20s-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a70-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a60-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a50-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a40-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a30-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a20-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a10-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a9-2018-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a7-2018-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a6-plus-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a6-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a8-star-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a8-plus-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a8-2018-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a7-2017-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a5-2017-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a3-2017-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a7-2016-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a5-2016-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-a3-2016-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-j8-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-j7-2017-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-j6-plus-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-j6-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-j5-2017-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-j4-plus-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-j4-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-j3-2017-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-j7-prime-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-j5-prime-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-j2-prime-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-j1-2016-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-j5-2016-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-j3-2016-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-j1-mini-prime-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-j1-nxt-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-j1-ace-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-j1-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-note-9-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-note-8-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-note-5-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-note-4-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-note-3-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s10-5g-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s10-plus-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s10-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s10e-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s9-plus-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s9-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s8-plus-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s8-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s7-edge-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s7-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s6-edge-plus-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s6-edge-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s6-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s5-neo-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s5-mini-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s5-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s4-mini-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s4-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s3-neo-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s3-mini-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s3-remonts/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/huawei-y5-2019-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p30-pro-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p30-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p30-lite-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p20-pro-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p20-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p20-lite-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p10-plus-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p10-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p10-lite-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p9-plus-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p9-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p9-lite-mini-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p9-lite-2017-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p9-lite-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p8-max-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p8-lite-2017-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p8-lite-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p8-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-mate-20-pro-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-mate-20-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-mate-20-lite-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-mate-10-pro-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-mate-10-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-mate-10-lite-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-mate-9-pro-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-mate-9-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-mate-8-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-mate-s-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-nova-5t-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-nova-4-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-nova-3i-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-nova-3-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-nova-2-plus-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-nova-2-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-y9-2019-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-y9-prime-2019-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-y7-2019-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-y7-prime-2018-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-y6-prime-2018-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-y6-2018-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-y5-2018-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-y7-2018-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-y7-2017-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-y6-2017-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-y5-2017-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-y3-2017-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-y6-ii-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-y5-ii-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-y3-ii-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-y6-pro-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-y6-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-y5-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-y3-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p-smart-2019-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p-smart-2018-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p-smart-plus-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/huawei-p-smart-z-remonts/', destination: '/telefonu-remonts/huawei', permanent: true },
      { source: '/oneplus-7-pro-remonts/', destination: '/telefonu-remonts/oneplus', permanent: true },
      { source: '/oneplus-7-remonts/', destination: '/telefonu-remonts/oneplus', permanent: true },
      { source: '/oneplus-6t-remonts/', destination: '/telefonu-remonts/oneplus', permanent: true },
      { source: '/oneplus-6-remonts/', destination: '/telefonu-remonts/oneplus', permanent: true },
      { source: '/oneplus-5t-remonts/', destination: '/telefonu-remonts/oneplus', permanent: true },
      { source: '/oneplus-5-remonts/', destination: '/telefonu-remonts/oneplus', permanent: true },
      { source: '/oneplus-3t-remonts/', destination: '/telefonu-remonts/oneplus', permanent: true },
      { source: '/oneplus-3-remonts/', destination: '/telefonu-remonts/oneplus', permanent: true },
      { source: '/oneplus-x-remonts/', destination: '/telefonu-remonts/oneplus', permanent: true },
      { source: '/oneplus-2-remonts/', destination: '/telefonu-remonts/oneplus', permanent: true },
      { source: '/oneplus-one-remonts/', destination: '/telefonu-remonts/oneplus', permanent: true },
      { source: '/lenovo-k6-note-remonts/', destination: '/telefonu-remonts/lenovo', permanent: true },
      { source: '/lenovo-k6-remonts/', destination: '/telefonu-remonts/lenovo', permanent: true },
      { source: '/lenovo-vibe-shot-remonts/', destination: '/telefonu-remonts/lenovo', permanent: true },
      { source: '/lenovo-vibe-s1-remonts/', destination: '/telefonu-remonts/lenovo', permanent: true },
      { source: '/lenovo-vibe-p1m-remonts/', destination: '/telefonu-remonts/lenovo', permanent: true },
      { source: '/lenovo-a6000-plus-remonts/', destination: '/telefonu-remonts/lenovo', permanent: true },
      { source: '/lenovo-a6000-remonts/', destination: '/telefonu-remonts/lenovo', permanent: true },
      { source: '/lenovo-a5000-remonts/', destination: '/telefonu-remonts/lenovo', permanent: true },
      { source: '/lenovo-a319-remonts/', destination: '/telefonu-remonts/lenovo', permanent: true },
      { source: '/lenovo-a316i-remonts/', destination: '/telefonu-remonts/lenovo', permanent: true },
      { source: '/lenovo-a328-remonts/', destination: '/telefonu-remonts/lenovo', permanent: true },
      { source: '/sony-xperia-xz3-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-xz2-premium-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-xz2-compact-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-xz2-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-xz1-compact-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-xz1-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-xz-premium-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-xz-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-x-compact-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-x-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-xa2-ultra-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-xa2-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-xa1-ultra-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-xa1-plus-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-xa1-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-xa-ultra-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-xa-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-m5-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-m4-aqua-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-z5-premium-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-z5-compact-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-z5-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-z3-plus-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-z3-compact-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-z3-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-z2-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-z1-compact-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-z1-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-z-ultra-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/sony-xperia-z-remonts/', destination: '/telefonu-remonts/sony', permanent: true },
      { source: '/iphone-xs-max-remonts/', destination: '/iphone-remonts/iphone-xs-max', permanent: true },
      { source: '/iphone-xs-remonts/', destination: '/iphone-remonts/iphone-xs', permanent: true },
      { source: '/iphone-xr-remonts/', destination: '/iphone-remonts/iphone-xr', permanent: true },
      { source: '/iphone-x-remonts/', destination: '/iphone-remonts/iphone-x', permanent: true },
      { source: '/iphone-8-plus-remonts/', destination: '/iphone-remonts/iphone-8-plus', permanent: true },
      { source: '/iphone-8-remonts/', destination: '/iphone-remonts/iphone-8', permanent: true },
      { source: '/iphone-7-plus-remonts/', destination: '/iphone-remonts/iphone-7-plus', permanent: true },
      { source: '/iphone-7-remonts/', destination: '/iphone-remonts/iphone-7', permanent: true },
      { source: '/iphone-6s-plus-remonts/', destination: '/iphone-remonts/iphone-6s-plus', permanent: true },
      { source: '/iphone-6s-remonts/', destination: '/iphone-remonts/iphone-6s', permanent: true },
      { source: '/iphone-6-plus-remonts/', destination: '/iphone-remonts/iphone-6-plus', permanent: true },
      { source: '/iphone-6-remonts/', destination: '/iphone-remonts/iphone-6', permanent: true },
      { source: '/iphone-se-2016-remonts/', destination: '/iphone-remonts/iphone-se-2016', permanent: true },
      { source: '/iphone-5s-remonts/', destination: '/iphone-remonts/iphone-5s', permanent: true },
      { source: '/iphone-5c-remonts/', destination: '/iphone-remonts/iphone-5c', permanent: true },
      { source: '/iphone-5-remonts/', destination: '/iphone-remonts/iphone-5', permanent: true },
      { source: '/apple-ipad-pro-remonts-12-9/', destination: '/plansetdatoru-remonts/ipad', permanent: true },
      { source: '/apple-ipad-pro-2-remonts-12-9/', destination: '/plansetdatoru-remonts/ipad', permanent: true },
      { source: '/apple-ipad-pro-2-remonts-10-5/', destination: '/plansetdatoru-remonts/ipad', permanent: true },
      { source: '/apple-ipad-pro-3-remonts-12-9/', destination: '/plansetdatoru-remonts/ipad', permanent: true },
      { source: '/apple-ipad-pro-4-remonts-11/', destination: '/plansetdatoru-remonts/ipad', permanent: true },
      { source: '/apple-ipad-pro-3-remonts-11/', destination: '/plansetdatoru-remonts/ipad', permanent: true },
      { source: '/apple-ipad-pro-4-remonts-12-9/', destination: '/plansetdatoru-remonts/ipad', permanent: true },
      { source: '/apple-ipad-pro-5-remonts-12-9/', destination: '/plansetdatoru-remonts/ipad', permanent: true },
      { source: '/apple-ipad-pro-5-remonts-11/', destination: '/plansetdatoru-remonts/ipad', permanent: true },
      { source: '/apple-ipad-pro-remonts-9-7/', destination: '/plansetdatoru-remonts/ipad', permanent: true },
      { source: '/apple-ipad-air-2-remonts-2/', destination: '/plansetdatoru-remonts/ipad', permanent: true },
      { source: '/macbook-remonts/', destination: '/datoru-remonts/apple', permanent: true },
      { source: '/macbook-pro-remonts/', destination: '/datoru-remonts/apple', permanent: true },
      { source: '/macbook-air-remonts/', destination: '/datoru-remonts/apple', permanent: true },
      { source: '/samsung-galaxy-a30-remonts-3/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s20-fe-remonts-2/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s10e-remonts-3/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-s23-fe-remonts-copy/', destination: '/telefonu-remonts/samsung', permanent: true },
      { source: '/samsung-galaxy-note-10-remonts-3/', destination: '/telefonu-remonts/samsung', permanent: true },
    ];
  },

  webpack: (config) => {
    config.resolve.alias = {
      ...config.resolve.alias,
      '@': path.resolve(process.cwd()),           // root alias
      '@lib': path.resolve(process.cwd(), 'lib'),
      '@data': path.resolve(process.cwd(), 'app/data'),
      '@sections': path.resolve(process.cwd(), 'app/(site)/sections'),
      '@screens': path.resolve(process.cwd(), 'app/(site)/screens'),
      '@ui': path.resolve(process.cwd(), 'app/(site)/ui'),
      '@styles': path.resolve(process.cwd(), 'app/styles'),
      '@components': path.resolve(process.cwd(), 'app/(site)/components'),
    };
    return config;
  },
};

export default nextConfig;
