import Link from 'next/link';
import { LuCheck, LuDroplets, LuTriangleAlert, LuX } from 'react-icons/lu';

import s from './WaterDamageSections.module.scss';

const COPY = {
  lv: {
    protection: { eyebrow:'Mitruma aizsardzība', title:'Vai iPhone tiešām ir ', accent:'ūdensizturīgs?', paragraphs:['Daudzi iPhone modeļi ir aprīkoti ar putekļu un mitruma aizsardzību, piemēram, IP67 vai IP68 klases aizsardzību. Tas nenozīmē, ka iPhone ir pilnībā ūdensdrošs vai ka to var droši lietot ūdenī. Aizsardzība tiek testēta kontrolētos apstākļos un laika gaitā var samazināties nodiluma, kritienu, remonta vai korpusa bojājumu dēļ.','Īpaši riskanti ir sālsūdens, baseina ūdens, saldi dzērieni un kafija, jo tie var atstāt nosēdumus un paātrināt oksidāciju. Ja parādās uzlādes, ekrāna, skaņas vai ieslēgšanās problēmas, ierīci labāk pārbaudīt servisā.'] },
    emergency: { eyebrow:'Pirmā palīdzība ierīcei', title:'Ko darīt uzreiz, ja ', accent:'iPhone samirka?', intro:'Rīkojies mierīgi un nepārbaudi telefonu ar lādētāju.', doTitle:'Dari', dontTitle:'Nedari', dos:['Izslēdz iPhone, ja tas vēl darbojas','Atvieno kabeli un nelādē','Noņem vāciņu un noslauki ārpusi','Turi uzlādes portu uz leju','Atstāj sausā vietā ar vieglu gaisa plūsmu','Pēc iespējas ātrāk piesaki diagnostiku'], donts:['Nelādē telefonu','Neliec iPhone rīsos','Nežāvē ar fēnu vai radiatoru','Nepūt ar kompresoru','Nebāz portā salveti vai vates kociņu','Nekrati telefonu agresīvi'], riceTitle:'Vai iPhone pēc ūdens jāliek rīsos?', rice:'Nē. Rīsi neiztīra šķidruma paliekas, sāļus, cukuru vai oksidācijas pēdas no telefona iekšpuses. Rīsu putekļi un daļiņas var nonākt uzlādes ligzdā. Labāk ierīci atvienot no strāvas, noslaucīt un turēt sausā vietā ar gaisa plūsmu.' },
    effects: { eyebrow:'Kas notiek ierīces iekšpusē', title:'Kā šķidrums ', accent:'bojā iPhone?', intro:'Lielu kaitējumu rada arī minerāli, sāls, cukurs un citi piemaisījumi, kas pēc izžūšanas paliek uz savienojumiem.', items:[['Oksidācija','Uz plates kontaktiem un savienojumiem veidojas pēdas, kas traucē elektriskam kontaktam.'],['Uzlādes problēmas','Mitrums ligzdā var radīt koroziju un problēmas ar kabeļa atpazīšanu.'],['Ekrāna un skāriena kļūmes','Ekrāns var mirgot, kļūt melns vai skāriens var darboties nestabili.'],['Skaņas problēmas','Skaļruņi un mikrofoni var skanēt klusi, čarkstēt vai darboties ar pārtraukumiem.'],['Vēlākas kļūmes','Telefons sākumā var darboties, bet pēc stundām vai dienām pārstāt lādēties vai ieslēgties.']] },
    price: { eyebrow:'Diagnostikas cena', title:'Ūdens bojājumu ', accent:'diagnostika', price:'no 50 €', repair:'Remonta cena tiek noteikta pēc diagnostikas', text:'Pilnu remonta cenu nevar godīgi noteikt tikai pēc modeļa vai ārējām pazīmēm. Vispirms jānovērtē šķidruma un oksidācijas izplatība un jāpārbauda uzlādes ligzda, ekrāns, baterija, skaņa, kamera un plates savienojumi.', cta:'Pieteikt diagnostiku' },
    technical: { eyebrow:'Tīrīšana un reālistiskas iespējas', title:'Ko var un ko nevar ', accent:'solīt?', cleaningTitle:'Kā tiek tīrīti šķidruma bojājumi?', cleaning:'Nepietiek tikai izžāvēt telefonu no ārpuses. Novērtējam skartās zonas un izmantojam elektronikai piemērotu tīrīšanu; ja nepieciešams, detaļām, kuras drīkst šādi apstrādāt, izmantojam ultraskaņas tīrīšanu. Pēc tam ierīci žāvējam, saliekam un pārbaudām.', promises:[['Varam pārbaudīt bojājuma apjomu','Nosakām, kur šķidrums ir nonācis un kuras funkcijas ir skartas.'],['Varam samazināt papildu bojājumu risku','Tīrīšana var palīdzēt noņemt mitruma un oksidācijas pēdas.'],['Nevaram garantēt pilnīgu atjaunošanu','Dziļu plates vai vairāku detaļu bojājumu gadījumā remonts var nebūt iespējams vai pamatots.'],['Ūdensizturību pēc remonta nesolām','Pēc šķidruma, kritiena vai atvēršanas sākotnējā mitruma aizsardzība var būt samazināta.']], dataTitle:'Vai iespējams saglabāt datus?', data:'Dažreiz ierīci iespējams stabilizēt pietiekami, lai piekļūtu fotogrāfijām, kontaktiem vai citiem datiem. To nevar garantēt — rezultāts ir atkarīgs no bojājuma dziļuma un plates stāvokļa. Ja dati ir prioritāte, pasaki to servisā uzreiz.' },
    models: { title:'Citi remonta veidi pēc ', accent:'iPhone modeļa', intro:'Ūdens bojājumu cena tiek noteikta pēc diagnostikas. Citu remontu cenas vari apskatīt esošajās iPhone modeļu lapās.', all:'Visi iPhone modeļi' },
  },
  ru: {
    protection: { eyebrow:'Защита от влаги', title:'Действительно ли iPhone ', accent:'водостойкий?', paragraphs:['Многие модели iPhone имеют защиту от пыли и влаги класса IP67 или IP68. Это не означает, что телефон полностью водонепроницаем или его безопасно использовать в воде. Защита тестируется в контролируемых условиях и может снижаться из-за износа, падений, ремонта или повреждения корпуса.','Особенно опасны морская и бассейновая вода, сладкие напитки и кофе: они оставляют осадок и ускоряют окисление. При проблемах с зарядкой, экраном, звуком или включением устройство лучше проверить в сервисе.'] },
    emergency: { eyebrow:'Первая помощь устройству', title:'Что делать сразу, если ', accent:'iPhone намок?', intro:'Действуйте спокойно и не проверяйте телефон зарядным устройством.', doTitle:'Делайте', dontTitle:'Не делайте', dos:['Выключите iPhone, если он ещё работает','Отсоедините кабель и не заряжайте','Снимите чехол и вытрите корпус','Держите разъём зарядки вниз','Оставьте в сухом месте с лёгким потоком воздуха','Как можно скорее запишитесь на диагностику'], donts:['Не заряжайте телефон','Не кладите iPhone в рис','Не сушите феном или на батарее','Не продувайте компрессором','Не вставляйте салфетку или ватную палочку в порт','Не трясите телефон'], riceTitle:'Нужно ли класть iPhone в рис?', rice:'Нет. Рис не удаляет остатки жидкости, соли, сахар и следы окисления внутри телефона. Пыль и частицы риса могут попасть в разъём зарядки. Лучше отключить питание, вытереть устройство и оставить его в сухом месте с потоком воздуха.' },
    effects: { eyebrow:'Что происходит внутри', title:'Как жидкость ', accent:'повреждает iPhone?', intro:'Вред наносят также минералы, соль, сахар и другие примеси, остающиеся на соединениях после высыхания.', items:[['Окисление','На контактах и соединениях появляются следы, нарушающие электрический контакт.'],['Проблемы с зарядкой','Влага в разъёме вызывает коррозию и проблемы с распознаванием кабеля.'],['Сбои экрана и сенсора','Экран может мерцать, стать чёрным, а сенсор — работать нестабильно.'],['Проблемы со звуком','Динамики и микрофоны могут звучать тихо, хрипеть или работать с перебоями.'],['Поздние неисправности','Сначала телефон может работать, а через несколько часов или дней перестать заряжаться или включаться.']] },
    price: { eyebrow:'Цена диагностики', title:'Диагностика после ', accent:'попадания жидкости', price:'от 50 €', repair:'Цена ремонта определяется после диагностики', text:'Полную цену нельзя честно определить только по модели или внешним признакам. Сначала проверяем распространение жидкости и окисления, разъём зарядки, экран, батарею, звук, камеру и соединения платы.', cta:'Записаться на диагностику' },
    technical: { eyebrow:'Очистка и реалистичные ожидания', title:'Что можно и нельзя ', accent:'обещать?', cleaningTitle:'Как очищают повреждения от жидкости?', cleaning:'Недостаточно высушить телефон снаружи. Оцениваем затронутые зоны и используем подходящую для электроники очистку; при необходимости применяем ультразвуковую очистку к деталям, которые допускают такую обработку. Затем сушим, собираем и проверяем устройство.', promises:[['Можем оценить повреждение','Определяем, куда попала жидкость и какие функции затронуты.'],['Можем снизить риск дальнейшего повреждения','Очистка помогает удалить следы влаги и окисления.'],['Не можем гарантировать полное восстановление','При глубоком повреждении платы или нескольких деталей ремонт может быть невозможен или нецелесообразен.'],['Не обещаем водостойкость после ремонта','После жидкости, падения или вскрытия первоначальная защита от влаги может снизиться.']], dataTitle:'Можно ли сохранить данные?', data:'Иногда устройство удаётся стабилизировать достаточно, чтобы получить доступ к фотографиям, контактам и другим данным. Гарантировать это нельзя — результат зависит от глубины повреждения и состояния платы. Если данные являются приоритетом, сообщите об этом сразу.' },
    models: { title:'Другие виды ремонта по ', accent:'модели iPhone', intro:'Цена ремонта после воды определяется диагностикой. Цены других ремонтов доступны на существующих страницах моделей iPhone.', all:'Все модели iPhone' },
  },
};

function Header({ data, id }) { return <header className={s.header}><span>{data.eyebrow}</span><h2 id={id}>{data.title}<em>{data.accent}</em></h2>{data.intro && <p>{data.intro}</p>}</header>; }
export function WaterProtection({ locale='lv' }) { const c=(COPY[locale]||COPY.lv).protection; return <section className={s.section}><div className={s.container}><Header data={c} id="water-protection-title"/><div className={s.editorial}>{c.paragraphs.map(p=><p key={p}>{p}</p>)}</div></div></section>; }
export function WaterEmergency({ locale='lv' }) { const c=(COPY[locale]||COPY.lv).emergency; return <section id="ko-darit" className={s.section}><div className={s.container}><Header data={c} id="water-emergency-title"/><div className={s.two}><Advice title={c.doTitle} items={c.dos} Icon={LuCheck}/><Advice title={c.dontTitle} items={c.donts} Icon={LuX} danger/></div><aside className={s.warning}><LuTriangleAlert/><div><h3>{c.riceTitle}</h3><p>{c.rice}</p></div></aside></div></section>; }
function Advice({title,items,Icon,danger=false}) { return <article className={`${s.advice} ${danger?s.danger:''}`}><h3>{title}</h3><ul>{items.map(x=><li key={x}><Icon/>{x}</li>)}</ul></article>; }
export function WaterEffects({ locale='lv' }) { const c=(COPY[locale]||COPY.lv).effects; return <section className={s.section}><div className={s.container}><Header data={c} id="water-effects-title"/><div className={s.effectGrid}>{c.items.map(([a,b])=><article key={a}><LuDroplets/><h3>{a}</h3><p>{b}</p></article>)}</div></div></section>; }
export function WaterDiagnosticPrice({ locale='lv' }) { const c=(COPY[locale]||COPY.lv).price; return <section id="cenas" className={s.section}><div className={s.container}><Header data={c} id="water-price-title"/><div className={s.price}><strong>{c.price}</strong><b>{c.repair}</b><p>{c.text}</p><a href="#pieteikties">{c.cta}</a></div></div></section>; }
export function WaterTechnical({ locale='lv' }) { const c=(COPY[locale]||COPY.lv).technical; return <section className={s.section}><div className={s.container}><Header data={c} id="water-technical-title"/><div className={s.editorial}><h3>{c.cleaningTitle}</h3><p>{c.cleaning}</p></div><div className={s.promiseGrid}>{c.promises.map(([a,b])=><article key={a}><h3>{a}</h3><p>{b}</p></article>)}</div><aside className={s.data}><h3>{c.dataTitle}</h3><p>{c.data}</p></aside></div></section>; }
export function WaterModelLinks({ locale='lv' }) { const c=(COPY[locale]||COPY.lv).models; const base=locale==='ru'?'/ru/remont-iphone':'/iphone-remonts'; const models=['iphone-15','iphone-14','iphone-13','iphone-12','iphone-11']; return <section className={s.section}><div className={s.container}><header className={s.header}><h2>{c.title}<em>{c.accent}</em></h2><p>{c.intro}</p></header><nav className={s.links}>{models.map(m=><Link key={m} href={`${base}/${m}`}>{m.replace('-', ' ').replace('iphone','iPhone')}</Link>)}<Link href={base}>{c.all}</Link></nav></div></section>; }
